### ISSUE TITLE
[IMPORTANT] A lot of this is my code, used without permission 

### ISSUE THREAD

**Issue by ProbablyComputingSquid** [OmegaGodzilla66/joshco-clicker#1]
I never gave my permission for you to use legacy code from OWT, some of this code is mine, nmd102s, and coolschnoodle's. Just because you made some of it doesn't mean you can use all of it. Especially on a bad project that doesn't even work. You still have a lot of legacy cold segments left over too.
Please delete and/or refactor realengine.py

Additionally, you are using the JoshEngine branding without our consent. Please cease and desist.

**Comment by OmegaGodzilla66** [comment]
This is stupid for two reasons. 
1. You never put a copyright license on it, therefore there is no legal claim. 
2. It's not something new, novel, or different. I could probably code one right now. Instead, I'm using this. It's not new or different. 
3. This isn't an issue with the code, if you have an issue please contact me directly, and we can settle it there. 
Thanks, 
OmegaGodzilla66
